/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import java.util.Random;

public class App {
  final static Random random = new Random();
  final static int maxRandomNumber = 4;// ランダムな数値の最大値(0～4)

  public String getGreeting() {
    return "こんにちは SEMonster";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    Monster monster = new Monster(random.nextInt(5), random.nextInt(maxRandomNumber + 1));
    System.out.println(monster.toString());
  }
}
